# Generated by Django 5.2 on 2025-04-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('seen', models.BooleanField(default=True)),
                ('learnt', models.BooleanField(default=False)),
                ('languages_learnt_in', models.JSONField(default=list)),
            ],
        ),
    ]
